### ISSUE TITLE
upgrade to phonegap 8.0.0

### ISSUE THREAD

**Issue by elbidone** [meumobi/IRmobi#273]
https://blog.phonegap.com/phonegap-8-0-0-now-on-phonegap-build-ios-upgraded-to-xcode-9-2-9f350f5f775d

**Comment by elbidone** [comment]
A compile error raised when upgrade to phonegap 8.0.0

```
...
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: compileSdkVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:456)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:590)
	at com.android.build.gradle.BasePlugin.lambda$null$3(BasePlugin.java:555)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
...
FAILURE: Build failed with an exception.

* Where:
Script '/onesignal-cordova-plugin/app-build-extras-onesignal.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> /app/AndroidManifest.xml (No such file or directory)
```

Seems to be due to `onesignal-cordova-plugin`

**Comment by elbidone** [comment]
upgrading `onesignal-cordova-plugin` to v2.4.4 solve the issue `compileSdkVersion is not specified`

**Comment by elbidone** [comment]
target attribute of onesignal's resource-file have been updated on latest release should update config.xml, chekck [here](https://documentation.onesignal.com/docs/customize-notification-icons#section-4-phonegap-build-pgb-ionic-cloud-build) for more details
